name: docker-build

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      tags-prefix:
        required: true
        type: string
      build-args:
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        timeout-minutes: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 5

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 1

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: improwised/ghar-image
          tags: |
            type=sha,prefix=${{ inputs.tags-prefix }}-,suffix=-{{date 'X'}}
            type=raw,prefix=${{ inputs.tags-prefix }}-,value=latest
        timeout-minutes: 1

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<'EOF' > ~/.m2/settings.xml
          ${{ vars.MAVEN_SETTINGS_XML }}
          EOF

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
